# Generated by Django 4.1.2 on 2022-10-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='related_tag', to='users_manage.tag'),
        ),
    ]
